#config for
# rim_train_failure_gather.py
# rim_train_reflect.py 

dbg: true # dbg option
to_reflect_jsl: rims_train_out/nov25/failed_METHOD_n3_numtrain1000_gpt4turbo_vT1.0_cT1.0_seed777.jsonl
    
verbal_T: 1. # temperature querying LLM for verbal outputs (e.g. cot, plan generation, reflection, etc.)
code_T: 1. # temperature querying LLM for code outputs (e.g. plan2code or pal)


n_llmquery: 5 # number of choices to be checked for failure 
seed: 777 # if I query with seed, it is deterministic but still random.



backbone: gpt4turbo # chatgpt, gpt4, gpt4turbo